#  _   _       _   ____  _            _
# | | | | ___ | |_| __ )| | ___   ___| | __
# | |_| |/ _ \| __|  _ \| |/ _ \ / __| |/ /
# |  _  | (_) | |_| |_) | | (_) | (__|   <
# |_| |_|\___/ \__|____/|_|\___/ \___|_|\_\
#
# (C) 2017 by surva network | https://github.com/survanetwork

# Language of the plugin messages
# Possible options are: en (English), de (German)
language: "en"

# Name of the world where the game is in
world: "world"

# How many players must be online that the block is active (prevent that one player is getting coins alone)
players: 3
